development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV["DATABASE_KEY"] %>
  username: <%= ENV["USERNAME_KEY"] %>
  password: <%= ENV["PASSWORD_KEY"] %>
test:
  adapter: mysql2
  database: test_listings_manager
  username: <%= ENV["USERNAME_KEY"] %>
  password: <%= ENV["PASSWORD_KEY"] %>
production:
  adapter: mysql2
  encoding: utf8
  database: sch_listings mydb
  username: <%= ENV["USERNAME_KEY"] %>
  password: <%= ENV["PASSWORD_KEY"] %>